stages:
  data_injection:
    cmd: python src/data_injection.py
    deps:
    - src/data_injection.py
    params:
    - data_injection.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/interim
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - data/interim
    params:
    - feature_engineering.max_features
    outs:
    - data/processed
  model_building:
    cmd: python src/model_building.py
    deps:
    - data/processed
    - src/model_building.py
    params:
    - model_building.n_estimators
    - model_building.random_state
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/model_eval.py
    deps:
    - models/model.pkl
    - src/model_eval.py
    metrics:
    - reports/metrics.json
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
